# Generated by Django 5.2.15 on 2026-06-14 17:25

from django.db import migrations, models


def mark_existing_unknown_items(apps, schema_editor):
    ReceiptItem = apps.get_model("receipts", "ReceiptItem")
    ReceiptItem.objects.filter(is_food=False, category="не определено").update(review_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_productusageevent_recipetemplate_and_more'),
        ('receipts', '0002_productkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='review_status',
            field=models.CharField(choices=[('processed', 'Обработано'), ('pending', 'Нужно проверить')], default='processed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['review_status', 'category'], name='receipts_re_review__8dbd4c_idx'),
        ),
        migrations.RunPython(mark_existing_unknown_items, migrations.RunPython.noop),
    ]
