# Generated by Django 5.2.15 on 2026-06-14 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


RECIPES = [
    ("Омлет", ["яйцо", "молоко", "сыр"], "Взбейте яйца с молоком, добавьте сыр и приготовьте на сковороде.", "завтрак", "яйца молоко сыр"),
    ("Тосты с сыром", ["хлеб", "сыр"], "Подрумяньте хлеб, добавьте сыр и прогрейте до расплавления.", "перекус", "хлеб сыр"),
    ("Рис с курицей", ["курица", "рис"], "Отварите рис, обжарьте курицу и соедините с гарниром.", "ужин", "курица рис"),
    ("Салат из томатов и огурцов", ["томат", "огурец"], "Нарежьте овощи, добавьте соль и немного масла.", "салат", "томат огурец овощи"),
    ("Творожный завтрак с бананом", ["творог", "банан"], "Смешайте творог с бананом, по желанию добавьте йогурт.", "завтрак", "творог банан"),
    ("Жаркое", ["картофель", "мясо"], "Нарежьте картофель и мясо, тушите вместе до мягкости.", "ужин", "картофель мясо"),
]


def seed_recipe_templates(apps, schema_editor):
    RecipeTemplate = apps.get_model("pantry", "RecipeTemplate")
    for title, ingredients, steps, category, tags in RECIPES:
        RecipeTemplate.objects.get_or_create(
            title=title,
            defaults={
                "required_ingredients": ingredients,
                "steps": steps,
                "category": category,
                "tags": tags,
                "prioritize_expiring": True,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('used', 'Использовал'), ('wasted', 'Выкинул')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('category_snapshot', models.CharField(blank=True, max_length=120)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('expiration_date_snapshot', models.DateField(blank=True, null=True)),
                ('wasted_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('required_ingredients', models.JSONField(default=list, verbose_name='Ключевые ингредиенты')),
                ('steps', models.TextField(verbose_name='Шаги')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Категория')),
                ('tags', models.CharField(blank=True, max_length=250, verbose_name='Теги')),
                ('prioritize_expiring', models.BooleanField(default=True, verbose_name='Приоритет скоропортящимся')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='productusageevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='pantry.product'),
        ),
        migrations.AddField(
            model_name='productusageevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usage_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipetemplate',
            index=models.Index(fields=['is_active', 'prioritize_expiring'], name='pantry_reci_is_acti_7e3592_idx'),
        ),
        migrations.AddIndex(
            model_name='productusageevent',
            index=models.Index(fields=['user', 'action', 'created_at'], name='pantry_prod_user_id_82730e_idx'),
        ),
        migrations.AddIndex(
            model_name='productusageevent',
            index=models.Index(fields=['user', 'wasted_expired'], name='pantry_prod_user_id_c28691_idx'),
        ),
        migrations.RunPython(seed_recipe_templates, migrations.RunPython.noop),
    ]
